### ISSUE TITLE
can't build on FreeBSD clang 6.0.0 due toUniqueAccess template black magic

### ISSUE THREAD

**Issue by Francesco149** [fourtf/chatterino2#646]
https://github.com/fourtf/chatterino2/blob/master/src/common/UniqueAccess.hpp#L58

this line, which I assume is a way to statically assert that T has a default constructor, throws a bunch of errors when compiling on FreeBSD.

removing the line fixes the issue and I was able to compile without further issues

I have no idea what clang/template quirk causes the errors and i haven't touched templates in years, but if this is asserting that the class has a default constructor why not just let it error on the actual default constructor call a few lines later?

clang version

```
% clang -v
FreeBSD clang version 6.0.0 (tags/RELEASE_600/final 326565) (based on LLVM 6.0.0)
Target: x86_64-unknown-freebsd11.2
Thread model: posix
InstalledDir: /usr/bin
```

here's the errors:

````
--- Application.o ---
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'live' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:103:32: note: in instantiation of template class 'chatterino::UniqueAccess<chatterino::TwitchChannel::StreamStatus>' requested here
    UniqueAccess<StreamStatus> streamStatus_;
                               ^
../src/providers/twitch/TwitchChannel.hpp:24:14: note: default member initializer declared here
        bool live = false;
             ^
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'rerun' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:25:14: note: default member initializer declared here
        bool rerun = false;
             ^
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'viewerCount' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:26:18: note: default member initializer declared here
        unsigned viewerCount = 0;
                 ^
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'submode' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:105:29: note: in instantiation of template class 'chatterino::UniqueAccess<chatterino::TwitchChannel::RoomModes>' requested here
    UniqueAccess<RoomModes> roomModes_;
                            ^
../src/providers/twitch/TwitchChannel.hpp:39:14: note: default member initializer declared here
        bool submode = false;
             ^
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'r9k' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:40:14: note: default member initializer declared here
        bool r9k = false;
             ^
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'emoteOnly' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:41:14: note: default member initializer declared here
        bool emoteOnly = false;
             ^
In file included from ../src/Application.cpp:9:
In file included from ../src/providers/twitch/PubsubClient.hpp:5:
In file included from ../src/providers/twitch/TwitchServer.hpp:7:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'slowMode' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:43:13: note: default member initializer declared here
        int slowMode = 0;
            ^
--- TwitchAccountManager.o ---
clang++ -c -Xclang -include-pch -Xclang chatterino/c++.pch -pipe -O2 -std=gnu++1y -Wall -Wno-unused-function -Wno-switch -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Werror=return-type -Wno-unused-local-typedef -Wno-unused-private-field -pthread -fPIC -DQT_DEPRECATED_WARNINGS -DPAJLADA_SETTINGS_NO_BOOST -DIRC_NAMESPACE=Communi -DBUILD_IRC_CORE -DBUILD_IRC_MODEL -DBUILD_IRC_UTIL -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../chatterino2 -I. -I../src -I../lib/rapidjson/include -I../lib/settings/include -I../lib/signals/include -I../lib/humanize/include -I../lib/fmt -I../lib/libcommuni/src/core -I../lib/libcommuni/include/IrcCore -I../lib/libcommuni/src/model -I../lib/libcommuni/include/IrcModel -I../lib/libcommuni/src/util -I../lib/libcommuni/include/IrcUtil -I../lib/websocketpp -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtSvg -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtMultimedia -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I/usr/local/include/libdrm -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o TwitchAccountManager.o ../src/providers/twitch/TwitchAccountManager.cpp
--- TwitchChannel.o ---
clang++ -c -Xclang -include-pch -Xclang chatterino/c++.pch -pipe -O2 -std=gnu++1y -Wall -Wno-unused-function -Wno-switch -Wno-deprecated-declarations -Wno-sign-compare -Wno-unused-variable -Wno-strict-aliasing -Werror=return-type -Wno-unused-local-typedef -Wno-unused-private-field -pthread -fPIC -DQT_DEPRECATED_WARNINGS -DPAJLADA_SETTINGS_NO_BOOST -DIRC_NAMESPACE=Communi -DBUILD_IRC_CORE -DBUILD_IRC_MODEL -DBUILD_IRC_UTIL -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -I../../chatterino2 -I. -I../src -I../lib/rapidjson/include -I../lib/settings/include -I../lib/signals/include -I../lib/humanize/include -I../lib/fmt -I../lib/libcommuni/src/core -I../lib/libcommuni/include/IrcCore -I../lib/libcommuni/src/model -I../lib/libcommuni/include/IrcModel -I../lib/libcommuni/src/util -I../lib/libcommuni/include/IrcUtil -I../lib/websocketpp -I/usr/local/include/qt5 -I/usr/local/include/qt5/QtSvg -I/usr/local/include/qt5/QtWidgets -I/usr/local/include/qt5/QtMultimedia -I/usr/local/include/qt5/QtGui -I/usr/local/include/qt5/QtNetwork -I/usr/local/include/qt5/QtCore -I. -I/usr/local/include -I/usr/local/include/libdrm -I/usr/local/include -I/usr/local/lib/qt5/mkspecs/freebsd-clang -o TwitchChannel.o ../src/providers/twitch/TwitchChannel.cpp
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'live' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:103:32: note: in instantiation of template class 'chatterino::UniqueAccess<chatterino::TwitchChannel::StreamStatus>' requested here
    UniqueAccess<StreamStatus> streamStatus_;
                               ^
../src/providers/twitch/TwitchChannel.hpp:24:14: note: default member initializer declared here
        bool live = false;
             ^
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'rerun' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:25:14: note: default member initializer declared here
        bool rerun = false;
             ^
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'viewerCount' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:26:18: note: default member initializer declared here
        unsigned viewerCount = 0;
                 ^
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'submode' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:105:29: note: in instantiation of template class 'chatterino::UniqueAccess<chatterino::TwitchChannel::RoomModes>' requested here
    UniqueAccess<RoomModes> roomModes_;
                            ^
../src/providers/twitch/TwitchChannel.hpp:39:14: note: default member initializer declared here
        bool submode = false;
             ^
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'r9k' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:40:14: note: default member initializer declared here
        bool r9k = false;
             ^
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'emoteOnly' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:41:14: note: default member initializer declared here
        bool emoteOnly = false;
             ^
In file included from ../src/providers/twitch/TwitchChannel.cpp:1:
In file included from ../src/providers/twitch/TwitchChannel.hpp:8:
../src/common/UniqueAccess.hpp:58:37: error: default member initializer for 'slowMode' needed within definition of enclosing class 'TwitchChannel' outside of member functions
    template <typename X = decltype(T())>
                                    ^
../src/providers/twitch/TwitchChannel.hpp:43:13: note: default member initializer declared here
        int slowMode = 0;
 ```

**Comment by pajlada** [comment]
I've noticed the same thing. The issue seems to be the fact that they're nested classes/structs. Moving them out of their parent class fixes the issue.
